const ayarlar = {
  TOKEN: "OTIwNDAzOTY2MzM5MTkwODA0.Ybj2_Q.VcGvVYfcg7BRJlZC0GAqZQgScEY", // ASSAGIYI OKU
  owner: "871362916241264645",
  prefix: "?",

};

module.exports = ayarlar;

//BOT TOKENINIZI EGER BOT GLITCHDE KALACAK
//ISE .ENV DOSYASINA
//EGER VDS YE KURACAK ISENIZ YUKARIYA 1. SATIRA YAZIN4